apiVersion: v1alpha1
group: management
scope: scratch
kind: HttpBasicCredential
title: Echo Credentials (Basic Secret)
name: echocredential
spec:
    description: Example HTTP basic credential using secret values.
    secret:
        name: scratchsecret
---
apiVersion: v1alpha1
group: management
scope: scratch
kind: APIKeyCredential
title: Echo Credentials (API Key Secret)
name: echocredential
spec:
    description: Example API Key credential using secret values.
    name: X-API-KEY
    in: header
    secret:
        name: scratchsecret
---
apiVersion: v1alpha1
group: management
scope: scratch
kind: HttpBearerCredential
title: Echo Credentials (Bearer)
name: echocredential
spec:
    description: Example Bearer credential.
    token: im_a_secret