apiVersion: v1alpha1
group: management
scope: scratch
kind: PathRoute
title: Route for Echo Server v1
name: echov1route
spec:
    virtualAPIDefinition: echov1
    cors: echocors
    auth: APIKeyAuthRule:echoauth
    prefix: /api/echo
    target:
        apiServiceInstance: echov1ars
        credential: HttpBasicCredential:echocredential
        #credential: HttpBearerCredential:echocredential
        #credential: APIKeyCredential:echocredential


