apiVersion: v1alpha1
group: management
scope: scratch
kind: PathRoute
title: Route for Echo Server v1
name: echov1route
spec:
    virtualAPIDefinition: echov1
    cors: echocors
    auth: JWTAuthRule:echoauth
    prefix: /api/echo
    route:
        apiServiceInstance: echov1ars
        credential: HttpBasicCredential:echocredential
